package Tests;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import Main.Reporter;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class PasswordRecoveryNegative {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  Reporter rp;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    rp = new Reporter();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void doAddToCart() throws Exception {

	rp.addSimple("<h2>Password recovery (negative case)</h2>");
	
	try {
		
		rp.add("preconditions"); 
		
	    // 1 | open | /index.php | 
		rp.add("// 1 | open | http://automationpractice.com/index.php | "); 
	    driver.get("http://automationpractice.com/index.php");
	    
	    // 2 | setWindowSize | 1674x988 | 
	    driver.manage().window().setSize(new Dimension(1674, 988));
	    
	    // 3 | click | linkText=Sign in | 
	    rp.add("// 2 | click | button \"Sign in\" | "); 
	    driver.findElement(By.linkText("Sign in")).click();
	    
	    // 4 | click | linkText=Forgot your password? | 
	    rp.add("// 3 | click | link \"Forgot your password?\" | "); 
	    driver.findElement(By.linkText("Forgot your password?")).click();
	    
	    rp.add("test steps"); 
	    
	    // 6 | type | id=email | dfhadfhdfhsfghfghfg@sdsgfd.ee
	    rp.add("// 4 | type | field \"Email address\": dfhadfhdfhsfghfghfg@sdsgfd.ee"); 
	    driver.findElement(By.id("email")).sendKeys("dfhadfhdfhsfghfghfg@sdsgfd.ee");
	    
	    // 7 | click | css=.button-medium:nth-child(1) > span | 
	    rp.add("// 5 | click | button \"Retrieve password\" | "); 
	    driver.findElement(By.cssSelector(".button-medium:nth-child(1) > span")).click();
	    
	    rp.add("expected result"); 
	    
	    // 8 | click | css=ol > li | 
	    rp.add("// 6 | find | text \"There is no account registered for this email address.\" | "); 
	    driver.findElement(By.xpath("//li[text()='There is no account registered for this email address.']"));


    rp.add("<b><font style=\"color:green;\">TEST PASSED!</font></b>");
    
	}
	  catch(Exception e){
		  e.printStackTrace();
		  rp.add("<p style=\"color:red;\">" + e.getMessage() + "</p>");
	  }
    
  }
}
