package Tests;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import Main.Reporter;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ProductDetailedView {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  Reporter rp;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    rp = new Reporter();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void doAddToCart() throws Exception {

	rp.addSimple("<h2>Product detailed view</h2>");
	
	try {
		rp.add("preconditions"); 	
    
	// 1 | open | /index.php | 
	rp.add("// 1 | open | http://automationpractice.com/index.php | ");
    driver.get("http://automationpractice.com/index.php");
    
    // 2 | setWindowSize | 1400x1000 | 
    //rp.add("// 2 | setWindowSize | 1400x1000 | ");
    driver.manage().window().setSize(new Dimension(1400, 1000));

    // 3 | click | css=.sfHover > a | 
    rp.add("// 2 | click | button \"T-shirts\" | ");
    driver.findElement(By.cssSelector("#block_top_menu > ul > li:nth-child(3)")).click();

    rp.add("test steps"); 	
    
    // 4 | click | css=.lnk_view > span | 
    rp.add("// 3 | click | product image | ");
    driver.findElement(By.className("product_img_link")).click();
    
    rp.add("expected result"); 	
    
    Thread.sleep(3000);
    
    // 5 | click | css=.button-medium > span | 
    rp.add("// 4 | find | text \"Faded Short Sleeve T-shirts\" | ");
    driver.findElement(By.xpath("//h1[text()='Faded Short Sleeve T-shirts']"));

    //product image
    rp.add("// 5 | find | element \"Product picture\" | ");
    driver.findElement(By.id("bigpic"));
    
    //description
    rp.add("// 6 | find | element \"Product description\" | ");
    driver.findElement(By.id("short_description_content"));
    
    //tweet
    rp.add("// 7 | find | button \"Tweet\" | ");
    driver.findElement(By.cssSelector("#center_column > div > div > div.pb-center-column.col-xs-12.col-sm-4 > p.socialsharing_product.list-inline.no-print > button.btn.btn-default.btn-twitter"));
    
    //share
    rp.add("// 8 | find | button \"Share\" | ");
    driver.findElement(By.cssSelector("#center_column > div > div > div.pb-center-column.col-xs-12.col-sm-4 > p.socialsharing_product.list-inline.no-print > button.btn.btn-default.btn-facebook"));
    
    //google+
    rp.add("// 9 | find | button \"Google+\" | ");
    driver.findElement(By.cssSelector("#center_column > div > div > div.pb-center-column.col-xs-12.col-sm-4 > p.socialsharing_product.list-inline.no-print > button.btn.btn-default.btn-google-plus"));
    
    //pinterest
    rp.add("// 10 | find | button \"Pinterest\" | ");
    driver.findElement(By.cssSelector("#center_column > div > div > div.pb-center-column.col-xs-12.col-sm-4 > p.socialsharing_product.list-inline.no-print > button.btn.btn-default.btn-pinterest"));
    
    //send to a friend
    rp.add("// 11 | find | button \"Send to a friend\" | ");
    driver.findElement(By.id("send_friend_button"));
    
    //print
    rp.add("// 12 | find | button \"Print\" | ");
    driver.findElement(By.className("print"));

    //data sheet
    rp.add("// 13 | find | text \"Data sheet\" | ");
    driver.findElement(By.xpath("//h3[text()='Data sheet']"));
    
    //more info
    rp.add("// 14 | find | text \"More info\" | ");
    driver.findElement(By.xpath("//h3[text()='More info']"));
    
    //reviews
    rp.add("// 15 | find | text \"Reviews\" | ");
    driver.findElement(By.xpath("//h3[text()='Reviews']"));
    
    //add to wishilist
    rp.add("// 16 | find | button \"Add to wishlist\" | ");
    driver.findElement(By.id("wishlist_button"));
    
    // 6 | click | css=.product_attributes | 
    rp.add("// 17 | find | text \"$16.51\" | ");
    driver.findElement(By.xpath("//span[text()='$16.51']"));

    // 7 | type | id=quantity_wanted | 2
    rp.add("// 18 | find | field \"Quantity\"");
    driver.findElement(By.id("quantity_wanted"));

    // 8 | select | id=group_1 | label=L
    rp.add("// 19 | find | field \"Size\"");
    driver.findElement(By.id("group_1"));
    
    // 9 | click | id=color_14 | 
    rp.add("// 20 | find | button \"Blue\" | ");
    driver.findElement(By.id("color_14"));
    
    // 10 | click | css=.exclusive > span | 
    rp.add("// 21 | find | button \"Add to cart\" | ");
    driver.findElement(By.cssSelector(".exclusive > span"));
    
    rp.add("<b><font style=\"color:green;\">TEST PASSED!</font></b>");
    
	}
	  catch(Exception e){
		  e.printStackTrace();
		  rp.add("<p style=\"color:red;\">" + e.getMessage() + "</p>");
	  }
    
  }
}
