package Tests;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import Main.Reporter;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SignIn {
	
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  Reporter rp;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    rp = new Reporter();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void doSignInSignOut() {

	rp.addSimple("<h2>Sign in</h2>");
	  
	try {
		rp.add("preconditions"); 	
		
	// 1 | open | /index.php | 
	rp.add("// 1 | open | http://automationpractice.com/index.php | ");  
    driver.get("http://automationpractice.com/index.php");
    
    // 2 | setWindowSize | 1400x1000 | 
    driver.manage().window().setSize(new Dimension(1400, 1000));
    
    // 3 | click | linkText=Sign in | 
    rp.add("// 2 | click | button \"Sign in\" | ");
    driver.findElement(By.linkText("Sign in")).click();
    
    rp.add("test steps"); 	
    
    // 4 | type | id=email | someone@somewhere.com
    rp.add("// 3 | type | field \"Email address\": someone@somewhere.com");
    driver.findElement(By.id("email")).sendKeys("someone@somewhere.com");
    
    // 5 | type | id=passwd | mypassword
    rp.add("// 4 | type | field \"Password\": mypassword");
    driver.findElement(By.id("passwd")).sendKeys("mypassword");
    
    // 6 | click | css=#SubmitLogin > span | 
    rp.add("// 5 | click | button \"Sign in\" | ");
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();

    rp.add("expected result"); 	
    
    // 7 | click | css=.standard-checkout > span | 
    rp.add("// 6 | find | text \"My account\" | ");
    driver.findElement(By.xpath("//span[text()='My account']"));
    
    // 8 | click | css=.standard-checkout > span | 
    rp.add("// 7 | find | button \"John Doe\" | ");
    driver.findElement(By.xpath("//span[text()='John Doe']"));
    
    // 9 | click | css=.standard-checkout > span | 
    rp.add("// 8 | find | button \"Home\" | ");
    driver.findElement(By.xpath("//span[text()=' Home']"));
    
    // 10 | click | css=.standard-checkout > span | 
    rp.add("// 9 | find | button \"Sign out\" | ");
    driver.findElement(By.xpath("//a[text()='Sign out']"));
    
    // 11 | click | css=.standard-checkout > span | 
    rp.add("// 10 | find | button \"Order history and details\" | ");
    driver.findElement(By.xpath("//span[text()='Order history and details']"));
    
    // 12 | click | css=.standard-checkout > span | 
    rp.add("// 11 | find | button \"My credit slips\" | ");
    driver.findElement(By.xpath("//span[text()='My credit slips']"));
    
    // 13 | click | css=.standard-checkout > span | 
    rp.add("// 12 | find | button \"My addresses\" | ");
    driver.findElement(By.xpath("//span[text()='My addresses']"));
    
    // 14 | click | css=.standard-checkout > span | 
    rp.add("// 13 | find | button \"My personal information\" | ");
    driver.findElement(By.xpath("//span[text()='My personal information']"));
    
    // 15 | click | css=.standard-checkout > span | 
    rp.add("// 14 | find | button \"My wishlists\" | ");
    driver.findElement(By.xpath("//span[text()='My wishlists']"));

    rp.add("<b><font style=\"color:green;\">TEST PASSED!</font></b>");
  }
	  catch(Exception e){
		  e.printStackTrace();
		  rp.add("<p style=\"color:red;\">" + e.getMessage() + "</p>");
	  }
  }
}
